### PR TITLE
Fixes #69: Game runs with any origin

### LINKED ISSUE #69: Bug: Worlds with origin != (000|000) are impossible
**Description**
When setting the world's origin to a value other than 0|0 the GeneratingView as well as the GameView fail to dislpay the world. When going to negative coordinates the world generation itself breaks.
There are several bugs that lead to this and they should all be fixed so that worlds can be generated, displaye and played on, independent of their origin.

### PR DESCRIPTION
**Pull request by Loomie**
- Generate mountain tops only inside the world
- Map Generation preview displays the whole world

### CODE REVIEW

File: model/mapgeneration/src/main/kotlin/de/gleex/pltcmd/model/mapgeneration/mapgenerators/intermediate/MountainTopHeightMapper.kt [hunk 1]
```diff
@@ -79,20 +78,33 @@ class MountainTopHeightMapper(override val rand: Random, override val context: G
...
             tries++
         }
 
         val pickedLocations = mutableSetOf<Coordinate>()
         pickedAreas.forEach { mainCoordinate ->
-            for(i in 0 until mountainTopsPerMainCoordinate)
-                pickedLocations.add(
-                        mainCoordinate.toCoordinate()
-                                .movedBy(rand.nextInt(100), rand.nextInt(100)))
+            for (i in 0 until mountainTopsPerMainCoordinate) {
```
Comment (Baret) [inline model/mapgeneration/src/main/kotlin/de/gleex/pltcmd/model/mapgeneration/mapgenerators/intermediate/MountainTopHeightMapper.kt:89]: `i` is unuesd so it could just be 
```suggestion
            repeat (mountainTopsPerMainCoordinate) {
```

File: model/mapgeneration/src/main/kotlin/de/gleex/pltcmd/model/mapgeneration/mapgenerators/intermediate/MountainTopHeightMapper.kt [hunk 2]
```diff
@@ -79,20 +78,33 @@ class MountainTopHeightMapper(override val rand: Random, override val context: G
...
+                val pickedLocation = pickRandomLocation(mainCoordinate, pickedLocations, mutableWorld)
+                pickedLocations.add(pickedLocation)
+            }
         }
         log.debug("Found ${pickedLocations.size} mountain top locations: ${pickedLocations.sorted()}")
         return pickedLocations.toSet()
     }
+
+    /** @return a random location inside the given []mainCoordinate] that is also in the given world and tries not to be in [pickedLocations] */
```
Comment (Baret) [inline model/mapgeneration/src/main/kotlin/de/gleex/pltcmd/model/mapgeneration/mapgenerators/intermediate/MountainTopHeightMapper.kt:98]:
```suggestion
    /** @return a random location inside the given [mainCoordinate] that is also in the given world and tries not to be in [pickedLocations] */
```

File: model/world/src/main/kotlin/de/gleex/pltcmd/model/world/WorldMap.kt [hunk 3]
```diff
@@ -75,15 +75,26 @@ data class WorldMap private constructor(private val originToSector: SortedMap<Co
...
     companion object {
         fun create(sectors: Iterable<Sector>): WorldMap = WorldMap(sectors.associateByTo(TreeMap(), Sector::origin))
     }
+
+    object Utils {
+        /**
+         * Ensures that the resulting position is inside the rectangle described by the given corners.
+         * @return the given Coordinate or the nearest at the border of the rectangle
+         **/
+        fun moveInside(location: Coordinate, bottomLeft: Coordinate, topRight: Coordinate): Coordinate {
```
Comment (Baret) [inline model/world/src/main/kotlin/de/gleex/pltcmd/model/world/WorldMap.kt:90]: This is unittested by the WorldMapTest (`WorldMap.moveInside()`), right?

File: game/ui/src/main/kotlin/de/gleex/pltcmd/game/ui/mapgeneration/PreviewGenerationListener.kt [hunk 4]
```diff
@@ -12,9 +12,16 @@ class PreviewGenerationListener(generatedWorldWidth: Int, generatedWorldHeight:
     private val displaySize = previewWorld.actualSize.to2DSize()
     private val tilesPerPreviewWidth = generatedWorldWidth / displaySize.width
     private val tilesPerPreviewHeight = generatedWorldHeight / displaySize.height
+    private var offsetX: Int? = null
```
[the remark this answers is not in the document]
Comment (Loomie) [reply game/ui/src/main/kotlin/de/gleex/pltcmd/game/ui/mapgeneration/PreviewGenerationListener.kt:15]: I wanted to use it, but didn't remembered the name. I tried `lazyinit` and `lazy` (what is a decorator) and because that hasn't worked I used `var`.

**Comment by Loomie** [comment]
> There is one bug though. When you scroll over the north/south 0-border, the left decoration shows "000" in the top left corner. Usually there is no coordinate shown there. Should be fixed.

Fixed.

File: game/ui/src/main/kotlin/de/gleex/pltcmd/game/ui/mapgeneration/PreviewGenerationListener.kt (hunk 4 above)
[the remark this answers is not in the document]
Comment (Loomie) [reply game/ui/src/main/kotlin/de/gleex/pltcmd/game/ui/mapgeneration/PreviewGenerationListener.kt:15]: :/
> 'lateinit' modifier is not allowed on properties of primitive types

File: model/world/src/main/kotlin/de/gleex/pltcmd/model/world/WorldMap.kt (hunk 3 above)
Comment (Loomie) [reply model/world/src/main/kotlin/de/gleex/pltcmd/model/world/WorldMap.kt:90]: Sure it is...

**Comment by Loomie** [comment]
Worked through the comments as well.
